name: Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GH_TOKEN }}
      - uses: docker/setup-qemu-action@v2 # v2
      - uses: docker/setup-buildx-action@v2 # v2
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: actions/cache@v3 # v3
        with:
          path: |
            ./dist/*.deb
            ./dist/*.rpm
            ./dist/*.apk
          key: ${{ github.ref }}
      - uses: sigstore/cosign-installer@v3.3.0
      - uses: anchore/sbom-action/download-syft@v0.15.1
      - uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - name: dockerhub-login
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: dckr_pat_4ySefz_ftSKgocuLY5hX-d0xO44
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: goreleaser-release
        run: task goreleaser


#      - run: git fetch --force --tags
#      - uses: actions/setup-go@v3
#        with:
#          go-version: '>=1.20.2'
#          cache: true
#      - uses: goreleaser/goreleaser-action@v4
#        with:
#          distribution: goreleaser
#          version: latest
#          args: release --clean
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
